// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfismionwystqhsmytjq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmaXNtaW9ud3lzdHFoc215dGpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2Mzk5MDcsImV4cCI6MjA3MDIxNTkwN30.IMSKjRsNhlCdwTzMmXUVV0gh60wrgPI82--TOkkzGd0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});